name: Run Python Script

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI


jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies (boto3 and requests)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests

      # Step 4: Set up AWS credentials (using GitHub secrets)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Modify with your region if necessary

      # Step 5: Run the Python script
      - name: Run Python script
        run: |
          python .github/workflows/combined_script.py  # Replace with your actual script file name
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Pass GitHub token as an environment variable
