name: Run Example Python Script

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Set the Python version (adjust as needed)

    - name: Install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install the 'requests' package directly

    - name: Run the Python script
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Pass the GitHub token as a secret
      run: python .github/workflows/example.py  # Run the Python script
